## Example and demos: https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos
## Official Doc: https://plugins.jenkins.io/configuration-as-code/#plugin-content-getting-started
jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin\n\n"
  nodes:
    - permanent:
        labelString: "linux docker terraform"
        mode: NORMAL
        name: "docker-agent"
        remoteFS: "/home/jenkins/agent"
        launcher:
          jnlp:
            workDirSettings:
              disabled: true
              failIfWorkDirIsMissing: false
              internalDir: "/home/jenkins/agent"
              workDirPath: "/tmp"



#Docs for DSL job using casc: https://github.com/jenkinsci/job-dsl-plugin/wiki/JCasC
jobs:
  - script: >
      freeStyleJob('SEED-JOB-CasC') {
          scm {
              github('ghebu/MariusLaboratory', 'main')
          }
          steps {
            dsl {
              external('Jenkins/JenkinsDockerfile/DSL/*.groovy')
              ignoreExisting(true)
              lookupStrategy("JENKINS_ROOT")
              removeViewAction("DELETE")
              removeAction("DELETE")
            }
          }
      }

