version: "3"
services:
  jenkins: 
    environment: 
      ADMIN_USERNAME: "ghebu"
      ADMIN_PASSWORD: "passw0rd"
    build: 
      context: JenkinsDockerfile
      dockerfile: Jenkins.Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - jenkins_home:/var/jenkins_home:Z
    ports:
      - 8080:8080
    privileged: true

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ghebu
      MONGO_INITDB_ROOT_PASSWORD: passw0rd
    volumes:
      - mongo_db:/data/db 
    ports:
      - 2717:27017
    

volumes: 
  jenkins_home:
  mongo_db:
