version: "3"
services:
  jenkins: 
    environment: 
      ADMIN_USERNAME: "ghebu"
      ADMIN_PASSWORD: "passw0rd"
    build: 
      context: JenkinsDockerfile
      dockerfile: Jenkins.Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - jenkins_home:/var/jenkins_home:Z
    ports:
      - 8080:8080
      - 50000:50000
    privileged: true 

  jenkins_agent: 
    environment: 
      JENKINS_AGENT_NAME: "docker-agent"
      JENKINS_URL: "http://jenkins:8080"
      TERRAFORM_VERSION: "0.13.1"
    build:
      context: JenkinsDockerfile
      dockerfile: JenkinsAgent.Dockerfile
      args:
        - TOKEN=21e82068c2902a21c7b329e7e46421a2db74278962c113b9631cf117e2880b1f
    healthcheck:
        test: ["CMD", "curl", "-f", "-u", "ghebu:passw0rd", "http://jenkins:8080"]
        interval: 30s
        timeout: 10s
        retries: 5
        start_period: 5s
    volumes:
      - jenkins_agent:/home/jenkins/agent:Z
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 22
      - 50000
    privileged: true


volumes: 
  jenkins_home:
  jenkins_agent:

