version: "3"
services:
  jenkins: 
    environment: 
      ADMIN_USERNAME: "ghebu"
      ADMIN_PASSWORD: "passw0rd"
    build: 
      context: JenkinsDockerfile
      dockerfile: Jenkins.Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - jenkins_home:/var/jenkins_home:Z
    ports:
      - 8080:8080
    privileged: true


volumes: 
  jenkins_home:

