version: "3"
services:
  jenkins: 
    #image: jenkins/jenkins:2.361.1-lts
    build: 
      context: JenkinsDockerfile
      dockerfile: Jenkins.Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - jenkins_home:/var/jenkins_home:Z
    ports:
      - 8080:8080
    privileged: true


volumes: 
  jenkins_home:

