version: "3"
services:
  jenkins: 
    environment: 
      ADMIN_USERNAME: "ghebu"
      ADMIN_PASSWORD: "passw0rd"
    build: 
      context: JenkinsDockerfile
      dockerfile: Jenkins.Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - jenkins_home:/var/jenkins_home:Z
    ports:
      - 8080:8080
      - 50000:50000
    privileged: true 

  jenkins_agent: 
    environment: 
      JENKINS_AGENT_NAME: "docker-agent"
      JENKINS_URL: "http://jenkins:8080"
      TERRAFORM_VERSION: "0.13.1"
    build:
      context: JenkinsDockerfile
      dockerfile: JenkinsAgent.Dockerfile
      args:
        - TOKEN=42738612c00c5d0b08cac7eb9d8e9a59ff036d673574a786e7bc96b9fcd3156a
    healthcheck:
        test: ["CMD", "curl", "-f", "-u", "ghebu:passw0rd", "http://jenkins:8080"]
        interval: 30s
        timeout: 10s
        retries: 5
        #start_period: 5s
    volumes:
      - jenkins_agent:/home/jenkins/agent:Z
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 22
      - 50000
    privileged: true

  victoriametrics: 
    build: 
      context: ../VictoriaMetrics
      dockerfile: Dockerfile
    volumes:
      - victoria_metrics:/victoria-metrics-data
    ports:
      - 8428:8428
    #privileged: true
  
  grafana: 
    image: grafana/grafana
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000

volumes: 
  jenkins_home:
  jenkins_agent:
  victoria_metrics:
  grafana:

